import { build } from 'esbuild';

const target = 'es2020';

await build({
  entryPoints: [
    'ts/index.ts',
    'ts/peerInitiator.ts',
    'ts/peerResponder.ts',
    'ts/dshake.types.ts',
  ],
  outdir: 'js',
  format: 'esm',
  platform: 'browser',
  target,
  bundle: false,
  sourcemap: false,
  logLevel: 'info',
});

await build({
  stdin: {
    contents: "import { createPeerInitiatorBridge } from './ts/peerInitiator.ts';\nwindow.createPeerInitiatorBridge = createPeerInitiatorBridge;",
    resolveDir: process.cwd(),
    sourcefile: 'peerInitiator.global.entry.ts',
    loader: 'ts',
  },
  outfile: 'js/peerInitiator.global.js',
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target,
  sourcemap: false,
  logLevel: 'info',
  banner: {
    js: '// Generated by scripts/build.mjs',
  },
});

await build({
  stdin: {
    contents: "import { createPeerResponderBridge } from './ts/peerResponder.ts';\nwindow.createPeerResponderBridge = createPeerResponderBridge;",
    resolveDir: process.cwd(),
    sourcefile: 'peerResponder.global.entry.ts',
    loader: 'ts',
  },
  outfile: 'js/peerResponder.global.js',
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target,
  sourcemap: false,
  logLevel: 'info',
  banner: {
    js: '// Generated by scripts/build.mjs',
  },
});
